CREATE TABLE tj_genre_jeux (
	GENRE_ID bigint(20) UNSIGNED NOT NULL,
	JEUX_ID bigint(20) UNSIGNED NOT NULL
);

CREATE TABLE tj_theme_jeux (
	THEME_ID bigint(20) UNSIGNED NOT NULL,
	JEUX_ID bigint(20) UNSIGNED NOT NULL
);

CREATE TABLE t_genre (
	GENRE_ID bigint(20) UNSIGNED NOT NULL,
	GENRE_LABEL varchar(80) NOT NULL,
	GENRE_DESCRIPTION mediumtext NOT NULL,
	GENRE_ILLUSTRATION varchar(80) NOT NULL
);

CREATE TABLE t_theme (
	THEME_ID bigint(20) UNSIGNED NOT NULL,
	THEME_LABEL varchar(80) NOT NULL,
	THEME_DESCRIPTION mediumtext NOT NULL,
	THEME_ILLUSTRATION varchar(80) NOT NULL
);

CREATE TABLE t_commentaire (
	COM_ID bigint(20) UNSIGNED NOT NULL,
	COM_TEXTE mediumtext NOT NULL,
	COM_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UTI_ID bigint(20) UNSIGNED DEFAULT NULL,
	JEUX_ID bigint(20) UNSIGNED NOT NULL
);

CREATE TABLE t_utilisateur (
	UTI_ID bigint(20) UNSIGNED NOT NULL,
	UTI_LOGIN varchar(255) NOT NULL,
	UTI_MAIL varchar(255) NOT NULL,
	UTI_NOM varchar(255) NOT NULL,
	UTI_PRENOM varchar(255) NOT NULL,
	UTI_PASS varchar(40) NOT NULL,
	UTI_ADMIN tinyint(1) NOT NULL DEFAULT 0,
	UTI_AVATAR varchar(80) DEFAULT NULL
);

CREATE TABLE t_jeux (
	JEUX_ID bigint(20) UNSIGNED NOT NULL,
	JEUX_DATE_SORTIE DATE NOT NULL,
	JEUX_TITRE varchar(80) NOT NULL,
	JEUX_SYNOPSYS longtext NOT NULL,
	JEUX_ILLUSTRATION varchar(80) NOT NULL,
	JEUX_EDITEUR varchar(80) NOT NULL,
	JEUX_DEVELOPPEUR varchar(80) NOT NULL,
	JEUX_MODE varchar(80) NOT NULL,
	JEUX_PLATEFORME varchar(80) NOT NULL,
	JEUX_CLASSIFICATION varchar(80) NOT NULL,
	UTI_ID bigint(20) UNSIGNED NOT NULL
);

ALTER TABLE tj_genre_jeux
  ADD PRIMARY KEY (GENRE_ID,JEUX_ID),
  ADD KEY GENRE_ID (GENRE_ID),
  ADD KEY JEUX_ID (JEUX_ID);

ALTER TABLE tj_theme_jeux
  ADD PRIMARY KEY (THEME_ID,JEUX_ID),
  ADD KEY THEME_ID (THEME_ID),
  ADD KEY JEUX_ID (JEUX_ID);

ALTER TABLE t_genre
  ADD PRIMARY KEY (GENRE_ID);

ALTER TABLE t_theme
  ADD PRIMARY KEY (THEME_ID);

ALTER TABLE t_commentaire
  ADD PRIMARY KEY (COM_ID),
  ADD KEY UTI_ID (UTI_ID),
  ADD KEY JEUX_ID (JEUX_ID);

ALTER TABLE t_utilisateur
  ADD PRIMARY KEY (UTI_ID),
  ADD UNIQUE KEY UTI_LOGIN (UTI_LOGIN);

ALTER TABLE t_jeux
  ADD PRIMARY KEY (JEUX_ID),
  ADD KEY UTI_ID (UTI_ID);

ALTER TABLE t_genre
  MODIFY GENRE_ID bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE t_theme
  MODIFY THEME_ID bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE t_commentaire
  MODIFY COM_ID bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE t_utilisateur
  MODIFY UTI_ID bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE t_jeux
  MODIFY JEUX_ID bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE tj_genre_jeux
  ADD CONSTRAINT FK_GENRE_JEUX FOREIGN KEY (GENRE_ID) REFERENCES t_genre (GENRE_ID),
  ADD CONSTRAINT FK_JEUX_GENRE FOREIGN KEY (JEUX_ID) REFERENCES t_jeux (JEUX_ID);

ALTER TABLE tj_theme_jeux
  ADD CONSTRAINT FK_THEME_JEUX FOREIGN KEY (THEME_ID) REFERENCES t_theme (THEME_ID),
  ADD CONSTRAINT FK_JEUX_THEME FOREIGN KEY (JEUX_ID) REFERENCES t_jeux (JEUX_ID);

ALTER TABLE t_commentaire
  ADD CONSTRAINT FK_COM_JEUX FOREIGN KEY (JEUX_ID) REFERENCES t_jeux (JEUX_ID),
  ADD CONSTRAINT FK_COM_UTI FOREIGN KEY (UTI_ID) REFERENCES t_utilisateur (UTI_ID);

ALTER TABLE t_jeux
  ADD CONSTRAINT FK_JEUX_UTI FOREIGN KEY (UTI_ID) REFERENCES t_utilisateur (UTI_ID);